pragmatic/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import *

app_name='accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    
]

pragmatic/pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', ArticleListView.as_view(), name='home'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('apartments/', include('apartmentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/profileapp/urls.py
from django.urls import path
from .views import*

app_name='profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

pragmatic/accountapp/models.py
from django.db import models

# Create your models here.

pragmatic/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from projectapp.models import Project

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='article') # 유저객체에서 article에 접근할 떄 쓰는 이름이라 writer이지만 article이라고 명한것.
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')

    title = models.CharField(max_length=200, null=True) # 제목을 꼭 적어야한다는 고정관념 탈피? ㅋ
    image = models.ImageField(upload_to='article/', null=False) #편의상 이미지는 항상 넣도록
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

pragmatic/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm 

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #여기까지만 쓰면 UserCreationForm 랑 똑같은 폼

        self.fields['username'].disabled = True

pragmatic/accountapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# reverse
from django.urls import reverse, reverse_lazy

#CRUD
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm #장고에서 제공해주는 유저 생성 폼
from accountapp.forms import AccountUpdateForm
from django.views.generic.list import MultipleObjectMixin

#데코레이터 관련
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import account_ownership_required

from articleapp.models import Article


has_ownership = [account_ownership_required, login_required]

# Create your views here.

class AccountCreateView(CreateView): #CBV만들떄 주요한 파라미터 만든다고했는데        
    model= User
    form_class = UserCreationForm # 계정은 중요한거라서 장고에서 폼을 제공해줌(만들필요 X )
    success_url = reverse_lazy('articleapp:list')  #성공했으면 가는 / 그리고 reverse_lazy는 클래스형에서 씀 
    template_name = 'accountapp/create.html'  #회원가입을 할 때 보일 비주얼폼 

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user' # 다른 사람이 와도 내 정보를 보게, 
    template_name = 'accountapp/detail.html'

    paginate_by = 10

    #ㅈㄴ 이해안되는 코드 ;;
    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)
    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model= User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('articleapp:list') 
    template_name = 'accountapp/update.html'  

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

pragmatic/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'accountapp:create'%}" method="post">
        {% csrf_token %}
        <!-- 이름,패스워드확인,이메일 다 만들고 스타일링하는게 아니라 이미 되어있는거, 제공한거 쓴거임 -->
        <!-- views.py에서 form_class = UserCreationForm 이렇게 지정해준거 이거임. -->
        <!-- {{ form }} -->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="가입">
    </form>
</div>


{% endblock %}

pragmatic/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>정말로 탈퇴하시겠습니까?</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-4" value="예">
    </form>
</div>


{% endblock %}

pragmatic/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}


<div>
    <div style="text-align: center; max-width:500px; margin:4rem auto;">

        <!-- 강의에선 없앴으나 그냥 남겨봄. -->
        <p>
            {{ target_user.date_joined }} 에 가입함
        </p>

       
        <!--프로필이 있으면 이미지도 보여주고  -->
        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt=""
        style="height: 12rem; width: 12rem; border-radius:20rem; margin-bottom:2rem; object-fit:cover;">

        <h2 style="font-family: 'NanumSquareB'">
            {{ target_user.profile.nickname }}
            {% if target_user == user %}
            
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
            class="material-icons" style="box-shadow: 0 0 10px #ccc; border-radius:10rem; padding: .4rem;">
                edit
            </a>
            
            {% endif %}
            <!-- 대화명 -->
        <h5 style="margin-bottom:3rem;">
            {{ target_user.profile.message }}
        </h5>
        </h2>
        <!-- 프로필이 없는 경우 본인일땐 Create Profile 본인이 아니면-->
        {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
        <h2 style="font-family: 'NanumSquareB'">
            Create Profile
        </h2>
        </a>
        <!-- 프로필이 없고 본인이 아닌경우 -->
        {% else %}
        <h2>
            닉네임이 없는 유저입니다.
        </h2>
        {% endif %}
        {% endif %}

        

        <!-- 지금보고있는 유저의 페이지의 유저와 들어와있는 유저가 같다면 보여줄게 -->
        {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=user.pk %}"
        class="material-icons" 
        style="box-shadow: 0 0 10px black; border-radius:10rem; padding: .4rem;">
            settings
        </a>
        
        <a href="{% url 'accountapp:delete' pk=user.pk %}"
        class="material-icons" 
        style="box-shadow: 0 0 10px indianred; border-radius:10rem; padding: .4rem;">
            cancel
        </a>
        {% endif %}

    </div>


    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>
</div>

{% endblock %}

pragmatic/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div>
    <div style="text-align: center;">
        <h4>Login</h4>
    </div>

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <form action="" method="post">
            {% csrf_token %}
            <!-- {{ form }} -->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="Login"> 
        </form>
    </div>
</div>

{% endblock %}

pragmatic/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Change Info</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <!-- 이름,패스워드확인,이메일 다 만들고 스타일링하는게 아니라 이미 되어있는거, 제공한거 쓴거임 -->
        <!-- views.py에서 form_class = UserCreationForm 이렇게 지정해준거 이거임. -->
        <!-- {{ form }} -->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="회원정보 수정">
    </form>
</div>


{% endblock %}