pragmatic/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import *

app_name='accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    
]

pragmatic/commentapp/urls.py
from django.urls import path 
from .views import *

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

pragmatic/pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', ArticleListView.as_view(), name='home'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('apartments/', include('apartmentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/commentapp/models.py
from django.db import models

from articleapp.models import Article
from django.contrib.auth.models import User

# Create your models here.



class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)

pragmatic/commentapp/forms.py
from django.forms import ModelForm
from commentapp.models import Comment

class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment 
        fields = ['content']

pragmatic/commentapp/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

# Create your views here.

#CRUD
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm #장고에서 제공해주는 유저 생성 폼
from accountapp.forms import AccountUpdateForm

#데코레이터 관련
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import comment_ownership_required

from .models import Comment
from .forms import CommentCreationForm
from articleapp.models import Article

class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'

    #아 이 코드가 이해가 더럽게 안된단 말이지....
    def form_valid(self, form):       
        temp_comment = form.save(commit=False)       
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])       
        temp_comment.writer = self.request.user          
        temp_comment.save()     
        return super().form_valid(form)       

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk }) #object는 코멘트고 코멘트를 단 article의 pk로 간다는것. 

@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'commentapp/delete.html'
    context_object_name = 'target_comment'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk }) #object는 코멘트고 코멘트를 단 article의 pk로 간다는것. 

pragmatic/commentapp/templates/commentapp/create.html
{% load bootstrap4 %}


<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Comment Create</h4>
    </div>
    <form action="{% url 'commentapp:create'%}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% if user.is_authenticated %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="작성">
        {% else %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}"
            class="btn btn-dark rounded-pill col-6 mt-4">
            Login
        </a>
        {% endif %}

        <!-- 이게 대체 왜 쓰인거지 대체 왜...? -->
        <input type="hidden" name="article_pk" value="{{ article.pk }}">
    </form>
</div>

pragmatic/commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Delete Comment : {{ target_comment.content }}</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-4" value="삭제">
    </form>
</div>


{% endblock %}

pragmatic/commentapp/templates/commentapp/detail.html
<div style="border:1px solid; text-align: left; padding:4%; margin: 1rem 0; border-radius:1rem; 
    border-color:#bbb">
    <div>
        <strong>
            {{ comment.writer.profile.nickname }}
        </strong>    
        &nbsp&nbsp&nbsp
        {{ comment.created_at }}
    </div>
    <div style="margin:1rem 0;">
        {{ comment.content }}
    </div>

    {% if comment.writer == user %}
    <div style="text-align: right;">
        <a href="{% url 'commentapp:delete' pk=comment.pk %}"
        class="btn btn-danger rounded-pill">
            Delete
        </a>
    </div>
    {% endif %}
</div>