pragmatic/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import*

app_name='articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
] 

pragmatic/pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', ArticleListView.as_view(), name='home'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('apartments/', include('apartmentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from projectapp.models import Project

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='article') # 유저객체에서 article에 접근할 떄 쓰는 이름이라 writer이지만 article이라고 명한것.
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')

    title = models.CharField(max_length=200, null=True) # 제목을 꼭 적어야한다는 고정관념 탈피? ㅋ
    image = models.ImageField(upload_to='article/', null=False) #편의상 이미지는 항상 넣도록
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

pragmatic/articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article
from projectapp.models import Project
from django import forms

class ArticleCreationForm(ModelForm):
    #게시글 쓸 때 위지윅 적용
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))
    
    #프로젝트다 불러오고 그와 동시에 고르지 않아도 되게끔.
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    class Meta:
        model = Article
        fields = ['title', 'image','project', 'content'] # writer는 서버내에서 설정해줄거다? 

pragmatic/articleapp/views.py
from django.shortcuts import render

# reverse
from django.urls import reverse, reverse_lazy

#CRUD
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm #장고에서 제공해주는 유저 생성 폼
from accountapp.forms import AccountUpdateForm
from django.views.generic.edit import FormMixin
from commentapp.forms import CommentCreationForm

#데코레이터 관련
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import account_ownership_required
from articleapp.decorators import article_ownership_required

# 모델
from articleapp.models import Article

#폼
from articleapp.forms import ArticleCreationForm


# Create your views here.

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    #아까 writer를 서버에서 지정해준다고 했잖음 / 프로필 앱의 뷰랑 비교하면서 코드 이해 ㄱㄱ
    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk })
    

class ArticleDetailView(DetailView, FormMixin):
    model = Article 
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk })
    

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article' # 꼭 쓸 필요는 없다고함
    template_name = 'articleapp/delete.html'
    success_url = reverse_lazy('articleapp:list')


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    success_url = reverse_lazy('articleapp:list')  
    paginate_by = 10   

pragmatic/articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Article Create</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'articleapp:create'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="게시">
    </form>
</div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

pragmatic/articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-4" value="삭제">
    </form>
</div>


{% endblock %}

pragmatic/articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}


<div>
    <div style="text-align: center; max-width:700px; margin:4rem auto;">

      <h1>{{ target_article.title }}</h1>

      <h6>
        작성자 : {{ target_article.writer.profile.nickname }}
      </h6>
      <hr>

      <img style="width:100%; border-radius:1rem; margin:2rem 0;" 
      src="{{ target_article.image.url }}" alt="">

      <!-- 위지윅 필터 걸어줌 -->
      <div class="text-left">
        {{ target_article.content | safe }}
      </div>

      {% if target_article.writer == user %}
      <a href="{% url 'articleapp:update' pk=target_article.pk %}"
        class="btn btn-primary rounded-pill col-3">
        Update
      </a>
      <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
        class="btn btn-danger rounded-pill col-3">
        Delete
      </a>
      {% endif %}
      <hr>

      <!-- target_article에 foreignkey로 엮여있는 코멘트를 전부 가져온다? -->
      {% for comment in target_article.comment.all %}
       {% include 'commentapp/detail.html' with comment=comment %}
      {% endfor %}

      {% include 'commentapp/create.html' with article=target_article %}

    </div>
</div>

{% endblock %}

pragmatic/articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<style>

.container {
  padding:0;
  margin:0, auto;
}

  /* 게시물들이 다 a태그로 감쌌으니까. */
.container a {
  width: 45%;
  max-width:250px; 
}

.container div {
  width: 250px;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 1rem;
}

.container img {
    width:100%;
    border-radius: 1rem;
}

</style>
{% if article_list %}
<div class="container">
  <!-- 각 게시물들 -->
  {% for article in article_list %}
  <a href="{% url 'articleapp:detail' pk=article.pk%}">
    {% include 'snippets/card.html' with article=article %}
  </a> 
  {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div class="text-center">
  <h1>No Article YET!</h1>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}


<div style="text-align: center;">
  <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
    Create Article
  </a>
</div>



{% endblock %}

pragmatic/articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Article Update</h4>
    </div>
    <!-- accoutapp에 있는 create로 라우팅해라. -->
    <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4" value="Apply">
    </form>
</div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}