pragmatic/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import *

app_name='accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    
]

pragmatic/apartmentapp/urls.py
from django.urls import path
from .views import *

app_name='apartmentapp'

urlpatterns = [
    path('predict/', my_form_view,  name='predict' )

]

pragmatic/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import*

app_name='articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
] 

pragmatic/pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', ArticleListView.as_view(), name='home'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('apartments/', include('apartmentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pragmatic/projectapp/urls.py
from django.urls import path
from .views import *


app_name = 'projectapp'


urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

pragmatic/templates/base.html
<!DOCTYPE html>
<html lang="ko">
 {% include 'head.html'%}
<body style="font-family: 'NanumSquareR' ">
    {% include 'header.html' %}
<hr>
    {% block content %}
    {% endblock %}
<hr>
    {% include 'footer.html' %}
</body>
</html>

pragmatic/templates/footer.html
<div class="pragmatic_footer">

    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>

</div>

pragmatic/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Pragmatic</title>
    
    <!-- 부트스트랩 css 4.6 링크 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


      <!-- 구글폰트 링크 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

      <!-- 구글 아이콘  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

     <!-- DEFAULT CSS LINK -->
     <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

     <style>
        @font-face {
          font-family: 'NanumSquareB';
          src: local('NanumSquareB'),
          url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype")
        }
  
        @font-face {
          font-family: 'NanumSquareEB';
          src: local('NanumSquareEB'),
          url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype")
        }
  
        @font-face {
          font-family: 'NanumSquareL';
          src: local('NanumSquareL'),
          url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype")
        }
  
        @font-face {
          font-family: 'NanumSquareR';
          src: local('NanumSquareR'),
          url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype")
        }
  
      </style>
</head>

pragmatic/templates/header.html
<!-- 제목이 있고 네비게이션바가 있다. -->
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">Pragmatic</h1>
    </div>

    <div class="pragmatic_header_navbar">
        <a href="{% url 'articleapp:list' %}"
        class="pragmatic_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}"
        class="pragmatic_header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}"
        class="pragmatic_header_nav">
            <span>Subscription</span>
        </a>
        {% if not user.is_authenticated %}
        </a>
        <a href="{% url 'apartmentapp:predict' %}"
        class="pragmatic_header_nav">
            <span>APT</span>
        </a>
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}"
        class="pragmatic_header_nav">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}"
        class="pragmatic_header_nav">
            <span>SignUp</span>
        {% else %}
        <a href="{% url 'apartmentapp:predict' %}"
        class="pragmatic_header_nav">
            <span>APT</span>
        </a>
        <!-- detail다음에pk받아와야하니까 pk=user.pk없으면 에러남 -->
        <a href="{% url 'accountapp:detail' pk=user.pk %}"
        class="pragmatic_header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}"
        class="pragmatic_header_nav">
            <span>logout</span>
        </a>
        {% endif %}

        
    </div>
</div>